Lab6/EducationGroups/EducationGroupsMVC/Controllers/CourseController.cs
using EducationGroupsMVC.Data;
using EducationGroupsMVC.Models;
using EducationGroupsMVC.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EducationGroupsMVC.Controllers
{
    public class CourseController : Controller
    {
        private readonly ApplicationDbContext _context;
        public CourseController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Create()
        {
            var teachers = await _context.Teachers.ToListAsync();
            var createCourseViewModel = new CreateCourseViewModel();
            foreach (var teacher in teachers)
            {
                createCourseViewModel.TeachersSelect.Add(new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem
                {
                    Text = teacher.FullName,
                    Value = teacher.Id.ToString()
                });
            }
            return View(createCourseViewModel);
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateCourseViewModel createCourseViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(createCourseViewModel);
            }
            var course = new Course
            {
                Name = createCourseViewModel.Name,
                Description = createCourseViewModel.Description,
                TeacherId = createCourseViewModel.TeacherId,
            };
            await _context.Courses.AddAsync(course);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }
        public async Task<IActionResult> Edit(int id)
        {
            var course = await _context.Courses.FindAsync(id);
            if (course is null)
            {
                return RedirectToAction("Index", "Home");
            }
            var editCourseViewModel = new EditCourseViewModel
            {
                Name = course.Name,
                Description = course.Description,
                TeacherId = course.TeacherId
            };
            var teachers = await _context.Teachers.ToListAsync();
            foreach (var teacher in teachers)
            {
                editCourseViewModel.TeachersSelect.Add(new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem
                {
                    Text = teacher.FullName,
                    Value = teacher.Id.ToString(),
                    Selected = course.TeacherId == teacher.Id
                });
            }
            return View(editCourseViewModel);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditCourseViewModel editCourseViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(editCourseViewModel);
            }
            var course = await _context.Courses.AsNoTracking().FirstOrDefaultAsync(s => s.Id == id);
            if (course is null)
            {
                return RedirectToAction("Index", "Home");
            }
            var newCourse = new Course
            {
                Id = id,
                Name= editCourseViewModel.Name,
                Description= editCourseViewModel.Description,
                TeacherId = editCourseViewModel.TeacherId
            };
            _context.Courses.Update(newCourse);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index", "Home");
            }
            var course = await _context.Courses.FindAsync(id);
            if (course is null)
            {
                return RedirectToAction("Index", "Home");
            }
            _context.Courses.Remove(course);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

Lab6/EducationGroups/EducationGroupsMVC/Controllers/HomeController.cs
using EducationGroupsMVC.Data;
using EducationGroupsMVC.Models;
using EducationGroupsMVC.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace EducationGroupsMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _context;

        public HomeController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var courses = await _context.Courses
                .Include(c => c.Teacher)
                .Include(c => c.Groups)
                .ThenInclude(g => g.Faculty)
                .ToListAsync();
            var students = _context.Students
                .Include(s => s.Group)
                .ThenInclude(g => g.Faculty);
            IndexHomeViewModel indexHomeViewModel = new()
            {
                Courses = courses,
                Students = students
            };
            return View(indexHomeViewModel);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Lab6/EducationGroups/EducationGroupsMVC/Controllers/StudentController.cs
using EducationGroupsMVC.Data;
using EducationGroupsMVC.Models;
using EducationGroupsMVC.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EducationGroupsMVC.Controllers
{
    public class StudentController : Controller
    {
        private readonly ApplicationDbContext _context;
        public StudentController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Create()
        {
            var groups = await _context.Groups.ToListAsync();
            var createStudentViewModel = new CreateStudentViewModel();
            foreach (var group in groups)
            {
                createStudentViewModel.GroupsSelect.Add(new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem
                {
                    Text = group.Name,
                    Value = group.Id.ToString()
                });
            }
            return View(createStudentViewModel);
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateStudentViewModel createStudentViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(createStudentViewModel);
            }
            var student = new Student
            {
                FullName = createStudentViewModel.FullName,
                Age = createStudentViewModel.Age,
                GroupId = createStudentViewModel.GroupId,
            };
            await _context.Students.AddAsync(student);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }
        public async Task<IActionResult> Edit(int id)
        {
            var student = await _context.Students.FindAsync(id);
            if (student is null)
            {
                return RedirectToAction("Index", "Home");
            }
            var editStudentViewModel = new EditStudentViewModel
            {
                FullName = student.FullName,
                Age = student.Age,
                GroupId = student.GroupId,
            };
            var groups = await _context.Groups.ToListAsync();
            foreach (var group in groups)
            {
                editStudentViewModel.GroupsSelect.Add(new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem
                {
                    Text = group.Name,
                    Value = group.Id.ToString(),
                    Selected = student.GroupId == group.Id
                });
            }
            return View(editStudentViewModel);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditStudentViewModel editStudentViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(editStudentViewModel);
            }
            var student = await _context.Students.AsNoTracking().FirstOrDefaultAsync(s => s.Id == id);
            if (student is null)
            {
                return RedirectToAction("Index", "Home");
            }
            var newStudent = new Student
            {
                Id = id,
                FullName = editStudentViewModel.FullName,
                Age = editStudentViewModel.Age,
                GroupId = editStudentViewModel.GroupId,
            };
            _context.Students.Update(newStudent);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index", "Home");
            }
            var student = await _context.Students.FindAsync(id);
            if (student is null)
            {
                return RedirectToAction("Index", "Home");
            }
            _context.Students.Remove(student);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

Lab6/EducationGroups/EducationGroupsMVC/Views/Home/Index.cshtml
@using EducationGroupsMVC.ViewModels;
@model IndexHomeViewModel
<div class="container">
    <div class="h1 d-flex align-items-center justify-content-between">
        <span>Курси:</span>
        <div>
            <a asp-controller="Course" class="btn btn-success" asp-action="Create">Додати курс</a>
        </div>
    </div>

    <table class="table">
        <thead>
            <tr>
				<th>ID</th>
                <th>Назва</th>
                <th>Опис</th>
                <th>Викладач</th>
                <th>Групи | Факультет</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var course in Model.Courses)
            {
                <tr >
                    <td>@course.Id</td>
                    <td>@course.Name</td>
                    <td>@course.Description</td>
                    <td>@course.Teacher.FullName</td>
                    <td>
                        @foreach(var group in course.Groups)
                        {
                            <p>@group.Name | @group.Faculty.Name</p>
                        }
                    </td>
                    <td style="text-align: right">
                        <a style="display: inline" asp-controller="Course" class="btn btn-primary" asp-route-id="@course.Id" asp-action="Edit">Редагувати</a>
                        <form style="display: inline" method="post" asp-action="Delete" asp-controller="Course" asp-route-id="@course.Id">
                            <button class="btn btn-danger">Видалити</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    
    <div class="h1 d-flex align-items-center justify-content-between mt-5">
        <span>Студенти:</span>
        <div>
            <a asp-controller="Student" class="btn btn-success" asp-action="Create">Додати студента</a>
        </div>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>ПІБ</th>
                <th>Вік</th>
                <th>Група</th>
                <th>Факультет</th>
                <th>Курс</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var student in Model.Students)
            {
                <tr>
                    <td>@student.Id</td>
                    <td>@student.FullName</td>
                    <td>@student.Age</td>
                    <td>@student.Group.Name</td>
                    <td>@student.Group.Faculty.Name</td>
                    <td>@student.Group.Course.Name</td>
                    <td style="text-align: right">
                        <a style="display: inline" asp-controller="Course" class="btn btn-primary" asp-route-id="@student.Id" asp-action="Edit">Редагувати</a>
                        <form style="display: inline" method="post" asp-action="Delete" asp-controller="Student" asp-route-id="@student.Id">
                            <button class="btn btn-danger">Видалити</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>